<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.2/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_QilYEPJjEeiRRNzlkYKbhg" name="POC-JCDecaux" author="bonitasoft" bonitaVersion="7.7.4" bonitaModelVersion="7.6.0-002" configId="ACED000574001C504F432D4A43446563617578372E362E302D303032372E372E347370">
    <elements xmi:type="process:Pool" xmi:id="_QilYEfJjEeiRRNzlkYKbhg" name="Gestion Project" welcomePageInternal="false" basedOnLookAndFeel="Default Application">
      <elements xmi:type="process:Lane" xmi:id="_QilYEvJjEeiRRNzlkYKbhg" name="Employé (lane)" actor="_QilYwfJjEeiRRNzlkYKbhg">
        <elements xmi:type="process:StartEvent" xmi:id="_QilYE_JjEeiRRNzlkYKbhg" name="Démarrer" outgoing="_QilYnfJjEeiRRNzlkYKbhg">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYFPJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QilYFfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QilYFvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QilYF_JjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_QilYGPJjEeiRRNzlkYKbhg" name="Initialisation Budget J0" outgoing="_pvrUkPMREei8R7BJ1_ftSQ" incoming="_QilYoPJjEeiRRNzlkYKbhg">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYGfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QilYGvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QilYG_JjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QilYHPJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QilYHfJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QilYHvJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QilYH_JjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QilYIPJjEeiRRNzlkYKbhg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QilYIfJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_QilYIvJjEeiRRNzlkYKbhg" name="Creation Project SAP" outgoing="_QilYoPJjEeiRRNzlkYKbhg" incoming="_QilYnfJjEeiRRNzlkYKbhg">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_F937wPMqEei8R7BJ1_ftSQ" source="_F9ycMPMqEei8R7BJ1_ftSQ"/>
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYI_JjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QilYJPJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QilYJfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QilYJvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QilYJ_JjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QilYKPJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QilYKfJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QilYKvJjEeiRRNzlkYKbhg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QilYK_JjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_QilYU_JjEeiRRNzlkYKbhg" name="Gestion ITS" outgoing="_qF4OEPMREei8R7BJ1_ftSQ" incoming="_pvrUkPMREei8R7BJ1_ftSQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYVPJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QilYVfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QilYVvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QilYV_JjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_dLrDoPMgEei8R7BJ1_ftSQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_dLrDofMgEei8R7BJ1_ftSQ" name="listConfigurations" content="listConfigurations" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:Data" xmi:id="_gksN4PMgEei8R7BJ1_ftSQ" name="listConfigurations" generated="false" multiple="true" dataType="_QilY1fJjEeiRRNzlkYKbhg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_dLrDovMgEei8R7BJ1_ftSQ" name="getConfigurationIds" content="import com.company.model.Configuration&#xD;&#xA;&#xD;&#xA;List&lt;Long> idsConfiguration = [];&#xD;&#xA;for(Configuration conf :project.getConfigurations()){&#xD;&#xA;&#x9;idsConfiguration.add(conf.persistenceId)&#xD;&#xA;}&#xD;&#xA;return idsConfiguration;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_sTjBsPMgEei8R7BJ1_ftSQ" name="project" dataType="_QilY2vJjEeiRRNzlkYKbhg" className="com.company.model.Project"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_dLrDo_MgEei8R7BJ1_ftSQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QilYWPJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QilYWfJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QilYWvJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QilYW_JjEeiRRNzlkYKbhg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QilYXPJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYXfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_QilYXvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_QilYX_JjEeiRRNzlkYKbhg">
            <targetForm xmi:type="expression:Expression" xmi:id="_QilYYPJjEeiRRNzlkYKbhg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_QilYYfJjEeiRRNzlkYKbhg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_QilYYvJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_1nmaQPMQEei8R7BJ1_ftSQ" name="Gestion Configuration" outgoing="__eDskPMREei8R7BJ1_ftSQ" incoming="_ZPI8oPMgEei8R7BJ1_ftSQ" type="PARALLEL" collectionDataToMultiInstantiate="_bF5C4PMgEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYRPJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_QilYRfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_QilYRvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_QilYR_JjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_QilYSPJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_QilYSfJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_QilYSvJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_QilYS_JjEeiRRNzlkYKbhg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Long" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_QilYTPJjEeiRRNzlkYKbhg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_1nmaRfMQEei8R7BJ1_ftSQ" name="Gestion Configuration" content="Gestion Configuration" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_1nmaRvMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="__eACMPMREei8R7BJ1_ftSQ" name="Fin" incoming="_L8YOcPMSEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="__eACNPMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__eACMvMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__eACMfMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__eACM_MREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_ES9mAPMSEei8R7BJ1_ftSQ" name="Porte2" outgoing="_Emnh0PMSEei8R7BJ1_ftSQ _ZPI8oPMgEei8R7BJ1_ftSQ" incoming="_qF4OEPMREei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ES9mBPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ES9mAvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ES9mAfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ES9mA_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_F-KjkPMSEei8R7BJ1_ftSQ" name="Porte3" outgoing="_F-gh0PMSEei8R7BJ1_ftSQ" incoming="__eDskPMREei8R7BJ1_ftSQ _GR7NEPMSEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_F-LKo_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_F-LKofMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_F-LKoPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_F-LKovMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_HRMRsPMSEei8R7BJ1_ftSQ" name="Review ITS" outgoing="_GR7NEPMSEei8R7BJ1_ftSQ" incoming="_Emnh0PMSEei8R7BJ1_ftSQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_EmlFk_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_EmlFkfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_EmlFkPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_EmlFkvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_EmlFlPMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_EmlFlfMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_EmlFlvMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_EmlFmPMSEei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_EmlFl_MSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_HRMRtfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_HRMRtvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_HRMRvfMSEei8R7BJ1_ftSQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_HRMRvvMSEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_HRMRvPMSEei8R7BJ1_ftSQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_HRMRv_MSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Activity" xmi:id="_L8AbAPMSEei8R7BJ1_ftSQ" name="Billan et cloture du project" outgoing="_L8YOcPMSEei8R7BJ1_ftSQ" incoming="_F-gh0PMSEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_L8BCE_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_L8BCEfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_L8BCEPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_L8BCEvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_L8BCFPMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_L8BCFfMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_L8BCFvMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_L8BCGPMSEei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_L8BCF_MSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_F9ycMPMqEei8R7BJ1_ftSQ" text="??"/>
      </elements>
      <resourceFolders xmi:type="process:ResourceFolder" xmi:id="_Qm3bIPJjEeiRRNzlkYKbhg" path="_QilYEfJjEeiRRNzlkYKbhg/application/application"/>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_QilYjvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_QilYj_JjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
      <errorTemplate xmi:type="process:AssociatedFile" xmi:id="_QilYkPJjEeiRRNzlkYKbhg" path="_5tpQYfJREeiRRNzlkYKbhg/html/error.html"/>
      <processTemplate xmi:type="process:AssociatedFile" xmi:id="_QilYkfJjEeiRRNzlkYKbhg" path="_QilYEfJjEeiRRNzlkYKbhg/html/process.html"/>
      <pageTemplate xmi:type="process:AssociatedFile" xmi:id="_QilYkvJjEeiRRNzlkYKbhg" path="_QilYEfJjEeiRRNzlkYKbhg/html/page.html"/>
      <consultationTemplate xmi:type="process:AssociatedFile" xmi:id="_QilYk_JjEeiRRNzlkYKbhg" path="_QilYEfJjEeiRRNzlkYKbhg/html/consultation.html"/>
      <data xmi:type="process:BusinessObjectData" xmi:id="_WQ5jgPMYEei8R7BJ1_ftSQ" name="project" dataType="_QilY2vJjEeiRRNzlkYKbhg" className="com.company.model.Project">
        <defaultValue xmi:type="expression:Expression" xmi:id="_WQ5jgfMYEei8R7BJ1_ftSQ" name="" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Object"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_bF5C4PMgEei8R7BJ1_ftSQ" name="listConfigurations" generated="false" multiple="true" dataType="_QilY1fJjEeiRRNzlkYKbhg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_cbxQsPMgEei8R7BJ1_ftSQ" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <confirmationTemplate xmi:type="process:AssociatedFile" xmi:id="_QilYlPJjEeiRRNzlkYKbhg" path="_QilYEfJjEeiRRNzlkYKbhg/html/_QilYEfJjEeiRRNzlkYKbhgconfirmation.html"/>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYlfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_QilYlvJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_QilYl_JjEeiRRNzlkYKbhg">
        <targetForm xmi:type="expression:Expression" xmi:id="_QilYmPJjEeiRRNzlkYKbhg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYmfJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_QilYmvJjEeiRRNzlkYKbhg">
        <targetForm xmi:type="expression:Expression" xmi:id="_QilYm_JjEeiRRNzlkYKbhg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_QilYnPJjEeiRRNzlkYKbhg" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QilYnfJjEeiRRNzlkYKbhg" target="_QilYIvJjEeiRRNzlkYKbhg" source="_QilYE_JjEeiRRNzlkYKbhg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QilYnvJjEeiRRNzlkYKbhg"/>
        <condition xmi:type="expression:Expression" xmi:id="_QilYn_JjEeiRRNzlkYKbhg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_QilYoPJjEeiRRNzlkYKbhg" target="_QilYGPJjEeiRRNzlkYKbhg" source="_QilYIvJjEeiRRNzlkYKbhg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_QilYofJjEeiRRNzlkYKbhg"/>
        <condition xmi:type="expression:Expression" xmi:id="_QilYovJjEeiRRNzlkYKbhg" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pvrUkPMREei8R7BJ1_ftSQ" target="_QilYU_JjEeiRRNzlkYKbhg" source="_QilYGPJjEeiRRNzlkYKbhg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pvrUkfMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_pvrUkvMREei8R7BJ1_ftSQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qF4OEPMREei8R7BJ1_ftSQ" target="_ES9mAPMSEei8R7BJ1_ftSQ" source="_QilYU_JjEeiRRNzlkYKbhg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qF41IPMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qF41IfMREei8R7BJ1_ftSQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__eDskPMREei8R7BJ1_ftSQ" target="_F-KjkPMSEei8R7BJ1_ftSQ" source="_1nmaQPMQEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__eEToPMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__eETofMREei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Emnh0PMSEei8R7BJ1_ftSQ" target="_HRMRsPMSEei8R7BJ1_ftSQ" source="_ES9mAPMSEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Emnh0fMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Emnh0vMSEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_F-gh0PMSEei8R7BJ1_ftSQ" target="_L8AbAPMSEei8R7BJ1_ftSQ" source="_F-KjkPMSEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_F-gh0fMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_F-gh0vMSEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_GR7NEPMSEei8R7BJ1_ftSQ" target="_F-KjkPMSEei8R7BJ1_ftSQ" source="_HRMRsPMSEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_GR7NEfMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_GR7NEvMSEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_L8YOcPMSEei8R7BJ1_ftSQ" target="__eACMPMREei8R7BJ1_ftSQ" source="_L8AbAPMSEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_L8YOcfMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_L8YOcvMSEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_ZPI8oPMgEei8R7BJ1_ftSQ" target="_1nmaQPMQEei8R7BJ1_ftSQ" source="_ES9mAPMSEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_ZPI8ofMgEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_ZPI8ovMgEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_QilYwfJjEeiRRNzlkYKbhg" documentation="Ceci est un exemple d'acteur associé à tous les utilisateurs d'ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_QilYwvJjEeiRRNzlkYKbhg"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_QilYw_JjEeiRRNzlkYKbhg">
        <name xmi:type="expression:Expression" xmi:id="_QilYxPJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QilYxfJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_QilYxvJjEeiRRNzlkYKbhg">
        <name xmi:type="expression:Expression" xmi:id="_QilYx_JjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QilYyPJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_QilYyfJjEeiRRNzlkYKbhg">
        <name xmi:type="expression:Expression" xmi:id="_QilYyvJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QilYy_JjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_QilYzPJjEeiRRNzlkYKbhg">
        <name xmi:type="expression:Expression" xmi:id="_QilYzfJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QilYzvJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_QilYz_JjEeiRRNzlkYKbhg">
        <name xmi:type="expression:Expression" xmi:id="_QilY0PJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_QilY0fJjEeiRRNzlkYKbhg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_dVux0PMQEei8R7BJ1_ftSQ" name="Gestion Configuration">
      <elements xmi:type="process:Lane" xmi:id="_dSZfEPMSEei8R7BJ1_ftSQ" name="Lane1" actor="_cAmgAPMSEei8R7BJ1_ftSQ">
        <elements xmi:type="process:StartEvent" xmi:id="_iN4zkPMQEei8R7BJ1_ftSQ" name="Démarrer" outgoing="_pd-9EPMQEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_iN5ao_MQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iN5aofMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iN5aoPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iN5aovMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_pwKSMPMQEei8R7BJ1_ftSQ" name="Chiffrage New Dev" outgoing="_1dLdgPMREei8R7BJ1_ftSQ" incoming="_pd-9EPMQEei8R7BJ1_ftSQ _1CHSIPMREei8R7BJ1_ftSQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_pdw6pPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_pdw6ovMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_pdw6ofMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_pdw6o_MQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_pdw6pfMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_pdw6pvMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_pdw6p_MQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_pdxhsPMQEei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_pdw6qPMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_pwK5RPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_pwK5RfMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_pwLgUfMQEei8R7BJ1_ftSQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_pwLgUvMQEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_pwLgUPMQEei8R7BJ1_ftSQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_pwLgU_MQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vhpIoPMQEei8R7BJ1_ftSQ" name="Validation New Dev" outgoing="_0D4IQPMREei8R7BJ1_ftSQ" incoming="_1dLdgPMREei8R7BJ1_ftSQ" overrideActorsOfTheLane="false">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_rlTZcPMREei8R7BJ1_ftSQ" source="_rlPvEPMREei8R7BJ1_ftSQ"/>
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_uVVtlPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uVVtkvMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uVVtkfMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uVVtk_MQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_uVVtlfMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_uVVtlvMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_uVVtl_MQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_uVVtmfMQEei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_uVVtmPMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_vhpvtPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_vhpvtfMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vhpvvPMQEei8R7BJ1_ftSQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_vhpvvfMQEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vhpvu_MQEei8R7BJ1_ftSQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vhpvvvMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_wxvekPMQEei8R7BJ1_ftSQ" name="Confirmation Auto SAP" outgoing="_7Llx0PMREei8R7BJ1_ftSQ" incoming="_0vkJkPMREei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_wxvelPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_wxvekvMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_wxvekfMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_wxvek_MQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_CSJxkPMiEei8R7BJ1_ftSQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_CSJxkfMiEei8R7BJ1_ftSQ" name="listActivities" content="listActivities" type="TYPE_VARIABLE" returnType="java.util.List">
              <referencedElements xmi:type="process:Data" xmi:id="_FKZKAPMiEei8R7BJ1_ftSQ" name="listActivities" generated="false" multiple="true" dataType="_QilY1fJjEeiRRNzlkYKbhg"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_CSJxkvMiEei8R7BJ1_ftSQ" name="s" content="import com.company.model.Activitie&#xD;&#xA;&#xD;&#xA;List&lt;Long> idsActivities = []&#xD;&#xA;&#xD;&#xA;for(Activitie act : configurations.getActivities()){&#xD;&#xA;&#x9;//We have to apply the order&#xD;&#xA;&#x9;idsActivities.add(act.persistenceId);&#xD;&#xA;}" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_isUIEPMoEei8R7BJ1_ftSQ" name="configurations" dataType="_QilY2vJjEeiRRNzlkYKbhg" className="com.company.model.Configuration"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_CSJxk_MiEei8R7BJ1_ftSQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_wxvelfMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_wxvelvMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_wxvel_MQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_wxwFoPMQEei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_wxvemPMQEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_rlPvEPMREei8R7BJ1_ftSQ" text="It send mail and set the task ready to validation"/>
        <elements xmi:type="process:XORGateway" xmi:id="_0Rtv8PMREei8R7BJ1_ftSQ" name="valide?" outgoing="_0vkJkPMREei8R7BJ1_ftSQ _1CHSIPMREei8R7BJ1_ftSQ" incoming="_0D4IQPMREei8R7BJ1_ftSQ" exclusiveOutgoingTransition="true">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_0D2TE_MREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_0D2TEfMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_0D2TEPMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_0D2TEvMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:CallActivity" xmi:id="_25m_QPMREei8R7BJ1_ftSQ" name="Activities dinamiques" outgoing="_altPUPMSEei8R7BJ1_ftSQ" incoming="_tnR6cPMgEei8R7BJ1_ftSQ" type="SEQUENTIAL">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_B6PQk_MREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_B6PQkfMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_B6PQkPMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_B6PQkvMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_B6PQlPMREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_B6PQlfMREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_B6PQlvMREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_B6PQmPMREei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_B6PQl_MREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <calledActivityName xmi:type="expression:Expression" xmi:id="_25nmVPMREei8R7BJ1_ftSQ" name="Activite" content="Activite" returnTypeFixed="true"/>
          <calledActivityVersion xmi:type="expression:Expression" xmi:id="_25nmVfMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_8gVXMPMREei8R7BJ1_ftSQ" name="Planification" outgoing="_AXlVkPMSEei8R7BJ1_ftSQ" incoming="_7Llx0PMREei8R7BJ1_ftSQ" type="PARALLEL" collectionDataToMultiInstantiate="_FGb3EPMiEei8R7BJ1_ftSQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_7LjVk_MREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_7LjVkfMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_7LjVkPMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_7LjVkvMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_7LjVlPMREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_7LjVlfMREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_7LjVlvMREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_7LjVmPMREei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Long" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_7LjVl_MREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_8gVXNfMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_8gVXNvMREei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_8gVXPfMREei8R7BJ1_ftSQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_8gVXPvMREei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_8gVXPPMREei8R7BJ1_ftSQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_8gVXP_MREei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_alqzEPMSEei8R7BJ1_ftSQ" name="Fin" incoming="_altPUPMSEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_alqzFPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_alqzEvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_alqzEfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_alqzE_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_tnFGIPMgEei8R7BJ1_ftSQ" name="Prepare activities" outgoing="_tnR6cPMgEei8R7BJ1_ftSQ" incoming="_AXlVkPMSEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_tnFGJPMgEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tnFGIvMgEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tnFGIfMgEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tnFGI_MgEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_vD7eoPMgEei8R7BJ1_ftSQ">
            <leftOperand xmi:type="expression:Expression" xmi:id="_vD7eofMgEei8R7BJ1_ftSQ" content=""/>
            <rightOperand xmi:type="expression:Expression" xmi:id="_vD7eovMgEei8R7BJ1_ftSQ" content=""/>
            <operator xmi:type="expression:Operator" xmi:id="_vD7eo_MgEei8R7BJ1_ftSQ" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_tnFGJfMgEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_tnFGJvMgEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_tnFGJ_MgEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_tnFGKfMgEei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_tnFGKPMgEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_dZhFovMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_dZhFofMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <data xmi:type="process:BusinessObjectData" xmi:id="_yR_WEPMgEei8R7BJ1_ftSQ" name="configurations" dataType="_QilY2vJjEeiRRNzlkYKbhg" className="com.company.model.Configuration">
        <defaultValue xmi:type="expression:Expression" xmi:id="_ba1tQPMiEei8R7BJ1_ftSQ" name="init_configurations()" content="&#xD;&#xA;&#xD;&#xA;configurationDAO.findByPersistenceId(configurationId)&#xD;&#xA;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Configuration">
          <referencedElements xmi:type="expression:Expression" xmi:id="_ba1tQfMiEei8R7BJ1_ftSQ" name="configurationDAO" content="configurationDAO" type="TYPE_BUSINESS_OBJECT_DAO" returnType="com.company.model.ConfigurationDAO" returnTypeFixed="true"/>
        </defaultValue>
      </data>
      <data xmi:type="process:Data" xmi:id="_-kkskPMhEei8R7BJ1_ftSQ" name="valide" dataType="_QilY0vJjEeiRRNzlkYKbhg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_-kkskfMhEei8R7BJ1_ftSQ" content="" returnType="java.lang.Boolean"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_FGb3EPMiEei8R7BJ1_ftSQ" name="listActivities" generated="false" multiple="true" dataType="_QilY1fJjEeiRRNzlkYKbhg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_FGb3EfMiEei8R7BJ1_ftSQ" content="" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List"/>
      </data>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_dZhFpPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_dZhFo_MQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_dZhFpvMQEei8R7BJ1_ftSQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_dZhFp_MQEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_dZhFpfMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_dZhFqPMQEei8R7BJ1_ftSQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_dZhFqfMQEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_dZhFoPMQEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pd-9EPMQEei8R7BJ1_ftSQ" target="_pwKSMPMQEei8R7BJ1_ftSQ" source="_iN4zkPMQEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pd_kIPMQEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_peALMPMQEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0D4IQPMREei8R7BJ1_ftSQ" target="_0Rtv8PMREei8R7BJ1_ftSQ" source="_vhpIoPMQEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0D4vUPMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0D4vUfMREei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_0vkJkPMREei8R7BJ1_ftSQ" name="oui" target="_wxvekPMQEei8R7BJ1_ftSQ" source="_0Rtv8PMREei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_0vkJkfMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_0vkJkvMREei8R7BJ1_ftSQ" name="valide" content="valide" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="__oPJAPMhEei8R7BJ1_ftSQ" name="valide" dataType="_QilY0vJjEeiRRNzlkYKbhg">
            <defaultValue xmi:type="expression:Expression" xmi:id="__oPJAfMhEei8R7BJ1_ftSQ" content="" returnType="java.lang.Boolean"/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1CHSIPMREei8R7BJ1_ftSQ" name="no" target="_pwKSMPMQEei8R7BJ1_ftSQ" source="_0Rtv8PMREei8R7BJ1_ftSQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1CHSIfMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1CHSIvMREei8R7BJ1_ftSQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1dLdgPMREei8R7BJ1_ftSQ" target="_vhpIoPMQEei8R7BJ1_ftSQ" source="_pwKSMPMQEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1dLdgfMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_1dLdgvMREei8R7BJ1_ftSQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_7Llx0PMREei8R7BJ1_ftSQ" target="_8gVXMPMREei8R7BJ1_ftSQ" source="_wxvekPMQEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_7LmY4PMREei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_7LmY4fMREei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AXlVkPMSEei8R7BJ1_ftSQ" target="_tnFGIPMgEei8R7BJ1_ftSQ" source="_8gVXMPMREei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AXlVkfMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_AXlVkvMSEei8R7BJ1_ftSQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_altPUPMSEei8R7BJ1_ftSQ" target="_alqzEPMSEei8R7BJ1_ftSQ" source="_25m_QPMREei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_alt2YPMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_alt2YfMSEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tnR6cPMgEei8R7BJ1_ftSQ" target="_25m_QPMREei8R7BJ1_ftSQ" source="_tnFGIPMgEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tnR6cfMgEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_tnR6cvMgEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_cAmgAPMSEei8R7BJ1_ftSQ" name="jcdecaux"/>
      <contract xmi:type="process:Contract" xmi:id="_dZhFqvMQEei8R7BJ1_ftSQ">
        <inputs xmi:type="process:ContractInput" xmi:id="_4LL-EPMgEei8R7BJ1_ftSQ" name="configurationId" type="LONG">
          <mapping xmi:type="process:ContractInputMapping" xmi:id="_4LL-EfMgEei8R7BJ1_ftSQ"/>
        </inputs>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dZgekPMQEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_dZgekfMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dZgekvMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dZgek_MQEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_dZgelPMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dZgelfMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dZgelvMQEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_dZgel_MQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dZgemPMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dZgemfMQEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_dZgemvMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dZgem_MQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_dZgenPMQEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_dZgenfMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_dZgenvMQEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <elements xmi:type="process:Pool" xmi:id="_ojmtkPMSEei8R7BJ1_ftSQ" documentation="This is a simple example of a subprocess to handle dinamic tasks" name="Activite">
      <elements xmi:type="process:Lane" xmi:id="_6aU3gPMSEei8R7BJ1_ftSQ" name="Lane2" actor="_4YQSEPMSEei8R7BJ1_ftSQ">
        <elements xmi:type="process:StartEvent" xmi:id="_uuC2kPMSEei8R7BJ1_ftSQ" name="Démarrer" outgoing="_u5Oy4PMSEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_uuDdo_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_uuDdofMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_uuDdoPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_uuDdovMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_vFnCAPMSEei8R7BJ1_ftSQ" name="Tache Dinamique" outgoing="_vdCDgPMSEei8R7BJ1_ftSQ" incoming="_u5Oy4PMSEei8R7BJ1_ftSQ" actor="_4YQSEPMSEei8R7BJ1_ftSQ" overrideActorsOfTheLane="false">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_u5MWo_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_u5MWofMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_u5MWoPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_u5MWovMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_u5MWpPMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_u5MWpfMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_u5MWpvMSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_u5MWqPMSEei8R7BJ1_ftSQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_u5MWp_MSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_vFnCBfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <confirmationMessage xmi:type="expression:Expression" xmi:id="_vFnCBvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_vFnCDfMSEei8R7BJ1_ftSQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_vFnCDvMSEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_vFnCDPMSEei8R7BJ1_ftSQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_vFnCD_MSEei8R7BJ1_ftSQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_vc_AMPMSEei8R7BJ1_ftSQ" name="Fin" incoming="_vdCDgPMSEei8R7BJ1_ftSQ">
          <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_vc_ANPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_vc_AMvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_vc_AMfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_vc_AM_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <mandatorySymbol xmi:type="expression:Expression" xmi:id="_ojnUsfMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <mandatoryLabel xmi:type="expression:Expression" xmi:id="_ojnUsPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <entryRedirectionURL xmi:type="expression:Expression" xmi:id="_ojnUs_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <confirmationMessage xmi:type="expression:Expression" xmi:id="_ojnUsvMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <formMapping xmi:type="process:FormMapping" xmi:id="_ojnUtfMSEei8R7BJ1_ftSQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ojnUtvMSEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <recapPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ojnUtPMSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_ojnUt_MSEei8R7BJ1_ftSQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_ojnUuPMSEei8R7BJ1_ftSQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <viewPageFlowRedirectionURL xmi:type="expression:Expression" xmi:id="_ojnUr_MSEei8R7BJ1_ftSQ" name="" content="" returnTypeFixed="true"/>
      <connections xmi:type="process:SequenceFlow" xmi:id="_u5Oy4PMSEei8R7BJ1_ftSQ" target="_vFnCAPMSEei8R7BJ1_ftSQ" source="_uuC2kPMSEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_u5Oy4fMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_u5PZ8PMSEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_vdCDgPMSEei8R7BJ1_ftSQ" target="_vc_AMPMSEei8R7BJ1_ftSQ" source="_vFnCAPMSEei8R7BJ1_ftSQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_vdCDgfMSEei8R7BJ1_ftSQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_vdCDgvMSEei8R7BJ1_ftSQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_4YQSEPMSEei8R7BJ1_ftSQ" name="jcdecaux"/>
      <contract xmi:type="process:Contract" xmi:id="_ojnUufMSEei8R7BJ1_ftSQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ojnUoPMSEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_ojnUofMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ojnUovMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ojnUo_MSEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_ojnUpPMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ojnUpfMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ojnUpvMSEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_ojnUp_MSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ojnUqPMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ojnUqfMSEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_ojnUqvMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ojnUq_MSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_ojnUrPMSEei8R7BJ1_ftSQ">
        <name xmi:type="expression:Expression" xmi:id="_ojnUrfMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_ojnUrvMSEei8R7BJ1_ftSQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_QilY0vJjEeiRRNzlkYKbhg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_QilY0_JjEeiRRNzlkYKbhg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_QilY1PJjEeiRRNzlkYKbhg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_QilY1fJjEeiRRNzlkYKbhg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_QilY1vJjEeiRRNzlkYKbhg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_QilY1_JjEeiRRNzlkYKbhg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_QilY2PJjEeiRRNzlkYKbhg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_QilY2fJjEeiRRNzlkYKbhg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_QilY2vJjEeiRRNzlkYKbhg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_QilY2_JjEeiRRNzlkYKbhg" type="Process" element="_QilYEPJjEeiRRNzlkYKbhg" name="MonDiagramme" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_QilY3PJjEeiRRNzlkYKbhg" type="2007" element="_QilYEfJjEeiRRNzlkYKbhg">
      <children xmi:type="notation:DecorationNode" xmi:id="_QilY3fJjEeiRRNzlkYKbhg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_QilY3vJjEeiRRNzlkYKbhg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_QilY3_JjEeiRRNzlkYKbhg" type="3007" element="_QilYEvJjEeiRRNzlkYKbhg">
          <children xmi:type="notation:DecorationNode" xmi:id="_QilY4PJjEeiRRNzlkYKbhg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_QilY4fJjEeiRRNzlkYKbhg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_QilY4vJjEeiRRNzlkYKbhg" type="3002" element="_QilYE_JjEeiRRNzlkYKbhg" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_QilY4_JjEeiRRNzlkYKbhg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QilY5PJjEeiRRNzlkYKbhg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QilY5fJjEeiRRNzlkYKbhg" x="60" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QilY5vJjEeiRRNzlkYKbhg" type="3006" element="_QilYGPJjEeiRRNzlkYKbhg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QilY5_JjEeiRRNzlkYKbhg" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QilY6PJjEeiRRNzlkYKbhg" x="346" y="118" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QilY6fJjEeiRRNzlkYKbhg" type="3027" element="_QilYIvJjEeiRRNzlkYKbhg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QilY6vJjEeiRRNzlkYKbhg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QilY6_JjEeiRRNzlkYKbhg" x="160" y="117" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QilY_PJjEeiRRNzlkYKbhg" type="3005" element="_QilYU_JjEeiRRNzlkYKbhg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_QilY_fJjEeiRRNzlkYKbhg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QilY_vJjEeiRRNzlkYKbhg" x="556" y="111" width="148" height="74"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1nnBUPMQEei8R7BJ1_ftSQ" type="3063" element="_1nmaQPMQEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1nnBUvMQEei8R7BJ1_ftSQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1nnBUfMQEei8R7BJ1_ftSQ" x="988" y="118" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__eBQUPMREei8R7BJ1_ftSQ" type="3062" element="__eACMPMREei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__eBQUvMREei8R7BJ1_ftSQ" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__eBQU_MREei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__eBQUfMREei8R7BJ1_ftSQ" x="1539" y="140"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ES9mBfMSEei8R7BJ1_ftSQ" type="3009" element="_ES9mAPMSEei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_ES-NEPMSEei8R7BJ1_ftSQ" visible="false" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ES-NEfMSEei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ES9mBvMSEei8R7BJ1_ftSQ" x="765" y="125"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F-LKpPMSEei8R7BJ1_ftSQ" type="3009" element="_F-KjkPMSEei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_F-LKpvMSEei8R7BJ1_ftSQ" visible="false" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_F-LKp_MSEei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F-LKpfMSEei8R7BJ1_ftSQ" x="1197" y="127"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_HRM4wPMSEei8R7BJ1_ftSQ" type="3005" element="_HRMRsPMSEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_HRM4wvMSEei8R7BJ1_ftSQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_HRM4wfMSEei8R7BJ1_ftSQ" x="1007" y="218" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_L8BpIPMSEei8R7BJ1_ftSQ" type="3006" element="_L8AbAPMSEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_L8BpIvMSEei8R7BJ1_ftSQ" type="5006"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_L8BpIfMSEei8R7BJ1_ftSQ" x="1349" y="130" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_F91fgPMqEei8R7BJ1_ftSQ" type="3015" element="_F9ycMPMqEei8R7BJ1_ftSQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_F91fhfMqEei8R7BJ1_ftSQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_F91fgfMqEei8R7BJ1_ftSQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_F91fgvMqEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_F91fg_MqEei8R7BJ1_ftSQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F91fhPMqEei8R7BJ1_ftSQ" x="202" y="27"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_QilZEPJjEeiRRNzlkYKbhg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_QilZEfJjEeiRRNzlkYKbhg" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_QilZEvJjEeiRRNzlkYKbhg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_QilZE_JjEeiRRNzlkYKbhg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QilZFPJjEeiRRNzlkYKbhg" x="45" y="10" width="1629" height="427"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_QilZFfJjEeiRRNzlkYKbhg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_QilZFvJjEeiRRNzlkYKbhg" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_QilZF_JjEeiRRNzlkYKbhg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_QilZGPJjEeiRRNzlkYKbhg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QilZGfJjEeiRRNzlkYKbhg" width="1680" height="250"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_dZ8jcPMQEei8R7BJ1_ftSQ" type="2007" element="_dVux0PMQEei8R7BJ1_ftSQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_daAN0PMQEei8R7BJ1_ftSQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_daA04PMQEei8R7BJ1_ftSQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_dSaGIPMSEei8R7BJ1_ftSQ" type="3007" element="_dSZfEPMSEei8R7BJ1_ftSQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_dSaGJfMSEei8R7BJ1_ftSQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_dSaGJvMSEei8R7BJ1_ftSQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_iN6BsPMQEei8R7BJ1_ftSQ" type="3002" element="_iN4zkPMQEei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_iN6owPMQEei8R7BJ1_ftSQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_iN6owfMQEei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_iN6BsfMQEei8R7BJ1_ftSQ" x="111" y="112"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_pwMHYPMQEei8R7BJ1_ftSQ" type="3005" element="_pwKSMPMQEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_pwNVgPMQEei8R7BJ1_ftSQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_pwMHYfMQEei8R7BJ1_ftSQ" x="217" y="112" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vhpvv_MQEei8R7BJ1_ftSQ" type="3005" element="_vhpIoPMQEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vhpvwfMQEei8R7BJ1_ftSQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vhpvwPMQEei8R7BJ1_ftSQ" x="426" y="112" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_wxwFofMQEei8R7BJ1_ftSQ" type="3027" element="_wxvekPMQEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_wxwssPMQEei8R7BJ1_ftSQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_wxwFovMQEei8R7BJ1_ftSQ" x="692" y="107" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_rlQ9MPMREei8R7BJ1_ftSQ" type="3015" element="_rlPvEPMREei8R7BJ1_ftSQ">
              <children xmi:type="notation:DecorationNode" xmi:id="_rlQ9NfMREei8R7BJ1_ftSQ" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_rlQ9MfMREei8R7BJ1_ftSQ"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_rlQ9MvMREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_rlQ9M_MREei8R7BJ1_ftSQ"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_rlQ9NPMREei8R7BJ1_ftSQ" x="578" y="36"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_0RuXAPMREei8R7BJ1_ftSQ" type="3008" element="_0Rtv8PMREei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_0RuXAvMREei8R7BJ1_ftSQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_0RuXA_MREei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_0RuXAfMREei8R7BJ1_ftSQ" x="597" y="115" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_25nmW_MREei8R7BJ1_ftSQ" type="3063" element="_25m_QPMREei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_25nmXfMREei8R7BJ1_ftSQ" type="5093"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_25nmXPMREei8R7BJ1_ftSQ" x="1186" y="107" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_8gV-QPMREei8R7BJ1_ftSQ" type="3005" element="_8gVXMPMREei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_8gV-QvMREei8R7BJ1_ftSQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_8gV-QfMREei8R7BJ1_ftSQ" x="901" y="112" width="106" height="53"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_alraIPMSEei8R7BJ1_ftSQ" type="3062" element="_alqzEPMSEei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_alraIvMSEei8R7BJ1_ftSQ" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_alsBMPMSEei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_alraIfMSEei8R7BJ1_ftSQ" x="1544" y="122"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tnFtMPMgEei8R7BJ1_ftSQ" type="3027" element="_tnFGIPMgEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_tnFtMvMgEei8R7BJ1_ftSQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tnFtMfMgEei8R7BJ1_ftSQ" x="1050" y="114"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_dSaGIfMSEei8R7BJ1_ftSQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_dSaGIvMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_dSaGI_MSEei8R7BJ1_ftSQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_dSaGJ_MSEei8R7BJ1_ftSQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dSaGJPMSEei8R7BJ1_ftSQ" x="188" y="91"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_dZ8jcfMQEei8R7BJ1_ftSQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_dZ8jcvMQEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_dZ8jc_MQEei8R7BJ1_ftSQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_daA04fMQEei8R7BJ1_ftSQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dZ8jdPMQEei8R7BJ1_ftSQ" width="1761" height="298"/>
    </children>
    <children xmi:type="notation:Node" xmi:id="_ojoiwPMSEei8R7BJ1_ftSQ" type="2007" element="_ojmtkPMSEei8R7BJ1_ftSQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_ojoixfMSEei8R7BJ1_ftSQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_ojoixvMSEei8R7BJ1_ftSQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_6aVekPMSEei8R7BJ1_ftSQ" type="3007" element="_6aU3gPMSEei8R7BJ1_ftSQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_6aVelfMSEei8R7BJ1_ftSQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_6aVelvMSEei8R7BJ1_ftSQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_uuDdpPMSEei8R7BJ1_ftSQ" type="3002" element="_uuC2kPMSEei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_uuEEsPMSEei8R7BJ1_ftSQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_uuEEsfMSEei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uuDdpfMSEei8R7BJ1_ftSQ" x="118" y="104"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vFnpEPMSEei8R7BJ1_ftSQ" type="3005" element="_vFnCAPMSEei8R7BJ1_ftSQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_vFnpEvMSEei8R7BJ1_ftSQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vFnpEfMSEei8R7BJ1_ftSQ" x="301" y="94" width="100" height="50"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_vdAOUPMSEei8R7BJ1_ftSQ" type="3062" element="_vc_AMPMSEei8R7BJ1_ftSQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_vdAOUvMSEei8R7BJ1_ftSQ" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_vdAOU_MSEei8R7BJ1_ftSQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_vdAOUfMSEei8R7BJ1_ftSQ" x="547" y="110"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_6aVekfMSEei8R7BJ1_ftSQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_6aVekvMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_6aVek_MSEei8R7BJ1_ftSQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_6aVel_MSEei8R7BJ1_ftSQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_6aVelPMSEei8R7BJ1_ftSQ" x="203" y="67"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_ojoiwfMSEei8R7BJ1_ftSQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_ojoiwvMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_ojoiw_MSEei8R7BJ1_ftSQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_ojoix_MSEei8R7BJ1_ftSQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ojoixPMSEei8R7BJ1_ftSQ" width="0" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_QilZGvJjEeiRRNzlkYKbhg"/>
    <edges xmi:type="notation:Connector" xmi:id="_QilZG_JjEeiRRNzlkYKbhg" type="4001" element="_QilYnfJjEeiRRNzlkYKbhg" source="_QilY4vJjEeiRRNzlkYKbhg" target="_QilY6fJjEeiRRNzlkYKbhg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QilZHPJjEeiRRNzlkYKbhg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QilZHfJjEeiRRNzlkYKbhg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QilZHvJjEeiRRNzlkYKbhg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QilZH_JjEeiRRNzlkYKbhg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_QilZIPJjEeiRRNzlkYKbhg" type="4001" element="_QilYoPJjEeiRRNzlkYKbhg" source="_QilY6fJjEeiRRNzlkYKbhg" target="_QilY5vJjEeiRRNzlkYKbhg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_QilZIfJjEeiRRNzlkYKbhg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_QilZIvJjEeiRRNzlkYKbhg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_QilZI_JjEeiRRNzlkYKbhg" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_QilZJPJjEeiRRNzlkYKbhg" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_peBZUPMQEei8R7BJ1_ftSQ" type="4001" element="_pd-9EPMQEei8R7BJ1_ftSQ" source="_iN6BsPMQEei8R7BJ1_ftSQ" target="_pwMHYPMQEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_peCncPMQEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_peDOgPMQEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_peBZUfMQEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_peBZUvMQEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pvr7oPMREei8R7BJ1_ftSQ" type="4001" element="_pvrUkPMREei8R7BJ1_ftSQ" source="_QilY5vJjEeiRRNzlkYKbhg" target="_QilY_PJjEeiRRNzlkYKbhg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pvsisPMREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pvsisfMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pvr7ofMREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pvr7ovMREei8R7BJ1_ftSQ" points="[0, -1, -164, 2]$[90, -1, -74, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pvtJwPMREei8R7BJ1_ftSQ" id="(1.0,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qF41IvMREei8R7BJ1_ftSQ" type="4001" element="_qF4OEPMREei8R7BJ1_ftSQ" source="_QilY_PJjEeiRRNzlkYKbhg" target="_ES9mBfMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qF5cMPMREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qF5cMfMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qF41I_MREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qF41JPMREei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qF6qUPMREei8R7BJ1_ftSQ" id="(1.0,0.44594594594594594)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rlUnkPMREei8R7BJ1_ftSQ" type="4003" element="_rlTZcPMREei8R7BJ1_ftSQ" source="_rlQ9MPMREei8R7BJ1_ftSQ" target="_vhpvv_MQEei8R7BJ1_ftSQ">
      <styles xmi:type="notation:FontStyle" xmi:id="_rlUnkfMREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rlUnkvMREei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0D4vUvMREei8R7BJ1_ftSQ" type="4001" element="_0D4IQPMREei8R7BJ1_ftSQ" source="_vhpvv_MQEei8R7BJ1_ftSQ" target="_0RuXAPMREei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0D4vVfMREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0D4vVvMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0D4vU_MREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0D4vVPMREei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_0vkJk_MREei8R7BJ1_ftSQ" type="4001" element="_0vkJkPMREei8R7BJ1_ftSQ" source="_0RuXAPMREei8R7BJ1_ftSQ" target="_wxwFofMQEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_0vkwoPMREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_0vkwofMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_0vkJlPMREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_0vkJlfMREei8R7BJ1_ftSQ" points="[-1, -6, -82, 0]$[52, -6, -29, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0vlXsPMREei8R7BJ1_ftSQ" id="(1.0,0.6511627906976745)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_0vlXsfMREei8R7BJ1_ftSQ" id="(0.24166666666666667,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1CJHUPMREei8R7BJ1_ftSQ" type="4001" element="_1CHSIPMREei8R7BJ1_ftSQ" source="_0RuXAPMREei8R7BJ1_ftSQ" target="_pwMHYPMQEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1CJHU_MREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1CJHVPMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1CJHUfMREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1CJHUvMREei8R7BJ1_ftSQ" points="[-22, 13, 351, 21]$[-22, 100, 351, 108]$[-373, 100, 0, 108]$[-373, 17, 0, 25]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1CKVcPMREei8R7BJ1_ftSQ" id="(1.0,0.6976744186046512)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_1dMEkPMREei8R7BJ1_ftSQ" type="4001" element="_1dLdgPMREei8R7BJ1_ftSQ" source="_pwMHYPMQEei8R7BJ1_ftSQ" target="_vhpvv_MQEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1dMEk_MREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1dMElPMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1dMEkfMREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1dMEkvMREei8R7BJ1_ftSQ" points="[0, -1, -124, 0]$[109, 1, -15, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1dMroPMREei8R7BJ1_ftSQ" id="(1.0,0.62)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_1dMrofMREei8R7BJ1_ftSQ" id="(0.15,0.6)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_7LmY4vMREei8R7BJ1_ftSQ" type="4001" element="_7Llx0PMREei8R7BJ1_ftSQ" source="_wxwFofMQEei8R7BJ1_ftSQ" target="_8gV-QPMREei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_7Lm_8PMREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_7Lm_8fMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_7LmY4_MREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_7LmY5PMREei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__eETovMREei8R7BJ1_ftSQ" type="4001" element="__eDskPMREei8R7BJ1_ftSQ" source="_1nnBUPMQEei8R7BJ1_ftSQ" target="_F-LKpPMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__eE6sPMREei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__eE6sfMREei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__eETo_MREei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__eETpPMREei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AXl8oPMSEei8R7BJ1_ftSQ" type="4001" element="_AXlVkPMSEei8R7BJ1_ftSQ" source="_8gV-QPMREei8R7BJ1_ftSQ" target="_tnFtMPMgEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AXl8o_MSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AXl8pPMSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AXl8ofMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AXl8ovMSEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AXnKwPMSEei8R7BJ1_ftSQ" id="(1.0,0.5471698113207547)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_EmoI4PMSEei8R7BJ1_ftSQ" type="4001" element="_Emnh0PMSEei8R7BJ1_ftSQ" source="_ES9mBfMSEei8R7BJ1_ftSQ" target="_HRM4wPMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_EmoI4_MSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_EmoI5PMSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_EmoI4fMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_EmoI4vMSEei8R7BJ1_ftSQ" points="[0, 22, -124, -74]$[0, 95, -124, -1]$[74, 95, -50, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F-hI4PMSEei8R7BJ1_ftSQ" type="4001" element="_F-gh0PMSEei8R7BJ1_ftSQ" source="_F-LKpPMSEei8R7BJ1_ftSQ" target="_L8BpIPMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_F-hI4_MSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_F-hI5PMSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_F-hI4fMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F-hI4vMSEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GR7NE_MSEei8R7BJ1_ftSQ" type="4001" element="_GR7NEPMSEei8R7BJ1_ftSQ" source="_HRM4wPMSEei8R7BJ1_ftSQ" target="_F-LKpPMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_GR70IPMSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_GR70IfMSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_GR7NFPMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GR7NFfMSEei8R7BJ1_ftSQ" points="[0, -9, -168, 94]$[168, -9, 0, 94]$[168, -81, 0, 22]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GR8bMPMSEei8R7BJ1_ftSQ" id="(1.0,0.66)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_L8YOc_MSEei8R7BJ1_ftSQ" type="4001" element="_L8YOcPMSEei8R7BJ1_ftSQ" source="_L8BpIPMSEei8R7BJ1_ftSQ" target="__eBQUPMREei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_L8Y1gPMSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_L8Y1gfMSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_L8YOdPMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_L8YOdfMSEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_alt2YvMSEei8R7BJ1_ftSQ" type="4001" element="_altPUPMSEei8R7BJ1_ftSQ" source="_25nmW_MREei8R7BJ1_ftSQ" target="_alraIPMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_alt2ZfMSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_alt2ZvMSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_alt2Y_MSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_alt2ZPMSEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_u5PZ8fMSEei8R7BJ1_ftSQ" type="4001" element="_u5Oy4PMSEei8R7BJ1_ftSQ" source="_uuDdpPMSEei8R7BJ1_ftSQ" target="_vFnpEPMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_u5PZ9PMSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_u5PZ9fMSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_u5PZ8vMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_u5PZ8_MSEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_vdCDg_MSEei8R7BJ1_ftSQ" type="4001" element="_vdCDgPMSEei8R7BJ1_ftSQ" source="_vFnpEPMSEei8R7BJ1_ftSQ" target="_vdAOUPMSEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_vdCDhvMSEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_vdCDh_MSEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_vdCDhPMSEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_vdCDhfMSEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_ZPJjsPMgEei8R7BJ1_ftSQ" type="4001" element="_ZPI8oPMgEei8R7BJ1_ftSQ" source="_ES9mBfMSEei8R7BJ1_ftSQ" target="_1nnBUPMQEei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_ZPJjs_MgEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_ZPJjtPMgEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_ZPJjsfMgEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_ZPJjsvMgEei8R7BJ1_ftSQ" points="[-4, -9, -244, 2]$[180, -9, -60, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_ZPKKwPMgEei8R7BJ1_ftSQ" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tnShgPMgEei8R7BJ1_ftSQ" type="4001" element="_tnR6cPMgEei8R7BJ1_ftSQ" source="_tnFtMPMgEei8R7BJ1_ftSQ" target="_25nmW_MREei8R7BJ1_ftSQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tnShg_MgEei8R7BJ1_ftSQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tnShhPMgEei8R7BJ1_ftSQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tnShgfMgEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tnShgvMgEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_F937wfMqEei8R7BJ1_ftSQ" type="4003" element="_F937wPMqEei8R7BJ1_ftSQ" source="_F91fgPMqEei8R7BJ1_ftSQ" target="_QilY6fJjEeiRRNzlkYKbhg">
      <styles xmi:type="notation:FontStyle" xmi:id="_F937wvMqEei8R7BJ1_ftSQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_F937w_MqEei8R7BJ1_ftSQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
